### ISSUE TITLE
Stopped working since 25 Nov

### ISSUE THREAD

**Issue by timbo80** [mitch-dc/volkswagen_we_connect_id#106]
Integration has been working fine but as of 25th November it has stopped working entirely.

I have another integration (https://github.com/skagmo/ha_vwid) which  also uses the VW APIs to pull similar data and it has also stopped working - perhaps the API has changed? The VW app still works.

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/volkswagen_we_connect_id/sensor.py:168
Integration: Volkswagen We Connect ID (documentation)
First occurred: 25 November 2022 at 11:51:30 (3043 occurrences)
Last logged: 16:55:41

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 348, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 669, in state
    value = self.native_value
  File "/config/custom_components/volkswagen_we_connect_id/sensor.py", line 236, in native_value
    state = get_object_value(self.entity_description.value(self.data.domains))
  File "/config/custom_components/volkswagen_we_connect_id/sensor.py", line 168, in <lambda>
    value=lambda data: data["vehicleHealthInspection"][
KeyError: 'vehicleHealthInspection'

**Comment by ColinRobbins** [comment]
I had this issue too.
It is solved by the pull request https://github.com/mitch-dc/volkswagen_we_connect_id/pull/103

**Comment by mitch-dc** [comment]
vehicleHealthInspection is not available in the api anymore since that date.. maby it comes back but i that just depends how VW feels. 

I'm looking into Colin Robbins PR.
