### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by drew-hill** [mitch-dc/volkswagen_we_connect_id#131]
I am unable to log in, with an "Unexpected Error" message in HA. Is there a log I can peruse for more info? Sorry to be a bit daft here!

Update: I found the log. Is this an issue caused by the fact that I'm in the US -- is this integration Europe-only?

2023-01-20 19:25:37.661 ERROR (MainThread) [custom_components.volkswagen_we_connect_id.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/volkswagen_we_connect_id/config_flow.py", line 64, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/volkswagen_we_connect_id/config_flow.py", line 39, in validate_input
    await hass.async_add_executor_job(we_connect.login)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 182, in login
    self.__session.login()
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
    response = self.doWebAuth(authorizationUrl)
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 198, in doWebAuth
    raise AuthentificationError(f'Error during login, account {self.sessionuser.username} does not exist')
weconnect.errors.AuthentificationError: Error during login, account <email address that I've censored> does not exist

**Comment by wipeout666** [comment]
I get the same error, details in the logs: 

Logger: custom_components.volkswagen_we_connect_id.config_flow
Source: custom_components/volkswagen_we_connect_id/config_flow.py:39
Integration: Volkswagen We Connect ID
First occurred: 12:47:05 PM (2 occurrences)
Last logged: 12:50:37 PM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/volkswagen_we_connect_id/config_flow.py", line 64, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/volkswagen_we_connect_id/config_flow.py", line 39, in validate_input
    await hass.async_add_executor_job(we_connect.login)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 182, in login
    self.__session.login()
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
    response = self.doWebAuth(authorizationUrl)
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 198, in doWebAuth
    raise AuthentificationError(f'Error during login, account {self.sessionuser.username} does not exist')
weconnect.errors.AuthentificationError: Error during login, account redacted@e-mail.com does not exist

**Comment by drew-hill** [comment]
I am also getting the same error messages when I attempt to connect via the python app itself:

Using `weconnect.WeConnect(username=args.username, password=args.password)`, I get the errors:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 115, in __init__
    self.update(updateCapabilities=updateCapabilities, updatePictures=updatePictures, selective=selective)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 191, in update
    self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 199, in updateVehicles
    data = self.fetchData(url, force)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 364, in fetchData
    statusResponse: requests.Response = self.session.get(url, allow_redirects=False)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 69, in request
    return super(WeConnectSession, self).request(
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/openid_session.py", line 192, in request
    url, headers, data = self.addToken(url, body=data, headers=headers, access_type=access_type, token=token)
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/openid_session.py", line 229, in addToken
    self.login()
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
    response = self.doWebAuth(authorizationUrl)
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 198, in doWebAuth
    raise AuthentificationError(f'Error during login, account {self.sessionuser.username} does not exist')
weconnect.errors.AuthentificationError: Error during login, account <email address I censored> does not exist

**Comment by wipeout666** [comment]
> I get the same error, details in the logs:
> 
> Logger: custom_components.volkswagen_we_connect_id.config_flow Source: custom_components/volkswagen_we_connect_id/config_flow.py:39 Integration: Volkswagen We Connect ID First occurred: 12:47:05 PM (2 occurrences) Last logged: 12:50:37 PM
> 
> Unexpected exception Traceback (most recent call last): File "/config/custom_components/volkswagen_we_connect_id/config_flow.py", line 64, in async_step_user info = await validate_input(self.hass, user_input) File "/config/custom_components/volkswagen_we_connect_id/config_flow.py", line 39, in validate_input await hass.async_add_executor_job(we_connect.login) File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 182, in login self.__session.login() File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 76, in login response = self.doWebAuth(authorizationUrl) File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 198, in doWebAuth raise AuthentificationError(f'Error during login, account {self.sessionuser.username} does not exist') weconnect.errors.AuthentificationError: Error during login, account [redacted@e-mail.com](mailto:redacted@e-mail.com) does not exist

Forgot to mention, canada ID.4

**Comment by mitch-dc** [comment]
This integration is only for cars in Europe. 

Canada and US use another app/api :( it's really annoying but i can't add support for these cars at the moment.

**Comment by drew-hill** [comment]
Makes total sense. Thank you for your response and for clearing that up for us! I may have missed it, but if it's not in your ReadMe already, a note to that effect might help future numb skulls like myself save some time and headache. Then again, why should that be your problem :). Thanks again!

**Comment by wipeout666** [comment]
Agree, quick note in the readme would help, especially since the US plant for ID.4 just opened few months ago; many US/Canada folks will be looking for the same thing.

**Comment by mitch-dc** [comment]
You guys are right! I've added a little note in the Readme and added it in the title :)

**Comment by drew-hill** [comment]
Thanks!
