### ISSUE TITLE
"Error doing job: Task exception was never retrieved" after upgrade to HA 2023.02

### ISSUE THREAD

**Issue by jthun** [mitch-dc/volkswagen_we_connect_id#138]
## Version of the custom_component

0.1.3

## Installation method (hacs / manual)
HACS

## Installation method of hass (venv, docker, hassio,...)
Docker on Synology

## Describe the bug

Not getting any values from the car after upgrading HA to 2023.02 stable.

## Debug log

```text
Logger: homeassistant
Source: custom_components/volkswagen_we_connect_id/number.py:67
Integration: Volkswagen We Connect ID
First occurred: 15:21:46 (17 occurrences)
Last logged: 15:53:42

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 135, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 390, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 566, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 607, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 356, in state
    return self.value
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 409, in value
    if (native_value := self.native_value) is None:
  File "/config/custom_components/volkswagen_we_connect_id/number.py", line 67, in native_value
    self.data.domains["charging"]["chargingSettings"].targetSOC_pct.value
KeyError: 'charging'

```

**Comment by jthun** [comment]
Values were updated after approx. two hours.
