### ISSUE TITLE
Entities suddenly went unavailable

### ISSUE THREAD

**Issue by jonas-wilnerzon** [mitch-dc/volkswagen_we_connect_id#146]
## Version of the custom_component

v0.1.3

## Installation method (hacs / manual)
I installed this integration using HACS.

## Installation method of hass (venv, docker, hassio,...)
HA

## Configuration
No config available since I cannot add the integration again after removing it.
```yaml

Add your configuration here.

```

## Describe the bug

I installed the integration as described and it worked as expected. But after the first drive with the car after installing the integration, the entities went unavailable, and the logs contained 404 errors and the stack trace below. I removed the integration and tried to login once again, giving me the same error as below.

## Debug log

```text

Traceback (most recent call last):
  File "/config/custom_components/volkswagen_we_connect_id/config_flow.py", line 64, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/volkswagen_we_connect_id/config_flow.py", line 39, in validate_input
    await hass.async_add_executor_job(we_connect.login)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 182, in login
    self.__session.login()
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 75, in login
    authorizationUrl = self.authorizationUrl(url='https://identity.vwgroup.io/oidc/v1/authorize')
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 96, in authorizationUrl
    redirect = tryLoginResponse.headers['Location']
  File "/usr/local/lib/python3.10/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'

```

**Comment by jonas-wilnerzon** [comment]
I didn't. See this (https://github.com/mitch-dc/volkswagen_we_connect_id/issues/143#issuecomment-1446812369) issue for comments regarding the error.
