### ISSUE TITLE
Issue with HA version 2023.3.0

### ISSUE THREAD

**Issue by robinostlund** [mitch-dc/volkswagen_we_connect_id#150]
Hi,
I just upgraded home assistant to version 2023.3.0 and i get this error now:
Unable to install package weconnect==0.54.1: ERROR: Cannot install weconnect==0.54.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip

I am running version 0.1.3 of this component and homeassistant running in docker 😄 

/ R

**Comment by PaulProjects** [comment]
duplicate of #149 

My "solution" till the next HA update is out
https://github.com/mitch-dc/volkswagen_we_connect_id/issues/149#issuecomment-1450869169

**Comment by robinostlund** [comment]
@PaulProjects oh missed that one, already tried that and i get this error instead :)

2023-03-01 23:27:46.790 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.volkswagen_we_connect_id.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/volkswagen_we_connect_id/sensor.py", line 100, in <module>
    device_class=SensorDeviceClass.energy,
  File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: energy
2023-03-01 23:27:46.791 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagen_we_connect_id.sensor: Platform not found (Exception importing custom_components.volkswagen_we_connect_id.sensor).

But will close this issue then, thanks

**Comment by PaulProjects** [comment]
yea #149 should be open for everyone who comes by to check on the problem.
And yea I get the same issue, after a few seconds the integration continues with the most of the entities missing
