### ISSUE TITLE
Dependency issue after upgrading to 2023.3.0

### ISSUE THREAD

**Issue by robinostlund** [mitch-dc/volkswagen_we_connect_id#152]
I have created a PR to see if it would be possible to downgrade requests version which is causing the dependency issue on the weconnect module (https://github.com/tillsteinbach/WeConnect-python/pull/109) as it seems that @mitch-dc PR to update HA with requests==2.28.2 wont be merged untill 2023.4.0 release (https://github.com/home-assistant/core/pull/88956)

@flixlix has created a PR which solves the sensor issue in #151 

Know that this has been discussed in #149 but i am creating a new issue as it is still not working.

**Comment by Ewoodster** [comment]
Same here: 

After installation and trying to set it up again, I am first greeted with this message:
Bitte warten, Konfigurationsassistent für Volkswagen We Connect ID wird gestartet
(Please wait, configuration asssitant for ID connect is being started)
 
followed by this message:
Fehler
Der Konfigurationsfluss konnte nicht geladen werden: 500 Internal Server Error Server got itself in trouble

**Comment by BaukeDeVries** [comment]
Also here the Dependency issue remains, and I would not like to miss my favorite HA Integration until the next HA release. Is a temporary fix possible?

**Comment by roppenheimer** [comment]
I got the error:

Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

When I tried to load the integration. I have upgraded HA Core to the latest version.

Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 9:42:05 AM (3 occurrences)
Last logged: 9:42:41 AM

Unable to install package weconnect==0.54.1: ERROR: Cannot install weconnect==0.54.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip

=======

Logger: aiohttp.server
Source: requirements.py:290
First occurred: 9:42:41 AM (1 occurrences)
Last logged: 9:42:41 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 67, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 148, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 831, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 849, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 955, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 385, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 52, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 171, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 186, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 252, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 290, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for volkswagen_we_connect_id not found: ['weconnect==0.54.1'].

**Comment by detlefh68** [comment]
Same error with HA 2023.3.0 and we connect id 0.14

 Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 09:40:52 (3 occurrences)
Last logged: 09:41:00
Unable to install package weconnect==0.54.1: ERROR: Cannot install weconnect==0.54.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip

**Comment by tsg21** [comment]
Same issue as in #70, which was not the first time we have seen this.

Seems like there is a bit of a flaw in the dependency management. HA requires a specific version of requests and will not tolerate any other, but the integration dependency management (in `manifest.json`) does not seem to give you a way to override transitive dependencies, such as those coming from the weconnect lib, which we cannot control here.

Not sure how to solve this!

**Comment by strutings** [comment]
Still the same issues with HA 2023.3.1. @mitch-dc is merged to this version, so it looks like there is another bug.

**Comment by geukster** [comment]
> Still the same issues with HA 2023.3.1. @mitch-dc ‘s PR is merged to this version, so it looks like there is another bug.

I'm now able to active heating and see the 'car active' status again, but still no milage or SoC...

**Comment by robinostlund** [comment]
Pending this PR #155 when that is released it will start working again 😄
