### ISSUE TITLE
Intergration error  async_setup_entry

### ISSUE THREAD

**Issue by Tassel8062** [mitch-dc/volkswagen_we_connect_id#162]
## Version of the custom_component
 
0.15

## Installation method (hacs / manual)
Hacs

## Installation method of hass (venv, docker, hassio,...)
Hassio

## Configuration

```yaml

Add your configuration here.

```

## Describe the bug

Intergration failing for over a week. Have upgraded HA to 2023.3.1 and the intergration to 0.15 and still failing to load 

## Debug log

```text

Add your logs here.

Log Details (ERROR)
This error originated from a custom integration.
Logger: homeassistant.config_entries
Source: custom_components/volkswagen_we_connect_id/__init__.py:47
Integration: Volkswagen We Connect ID
First occurred: 20:10:40 (1 occurrences)
Last logged: 20:10:40

Error setting up entry Volkswagen We Connect ID for volkswagen_we_connect_id
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 47, in async_setup_entry
    await hass.async_add_executor_job(_we_connect.login)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 184, in login
    self.__session.login()
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
    response = self.doWebAuth(authorizationUrl)
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 243, in doWebAuth
    raise APICompatibilityError('No user id provided')
weconnect.errors.APICompatibilityError: No user id provided


```

**Comment by KoalaWerewolf** [comment]
I have the same issue.

**Comment by jonasbkarlsson** [comment]
You have to login at myvolkswagen.de and accept the terms and conditions.
That solved it for me.

**Comment by KoalaWerewolf** [comment]
> You have to login at myvolkswagen.de and accept the terms and conditions.
> That solved it for me.

Thanks! I was not aware that this has become a recurring requirement.

**Comment by SwannyBFC** [comment]
I've logged onto myVolkswagen co uk and accepted the agreement, and the intergration is still not loading. I also did this a few weeks ago and it fixed the issue last time.

Error logs after accepting the agreement today 

2023-03-05 19:13:12.844 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.volkswagen_we_connect_id.sensor
2023-03-05 19:13:12.849 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagen_we_connect_id.sensor: Platform not found (Exception importing custom_components.volkswagen_we_connect_id.sensor).

**Comment by KoalaWerewolf** [comment]
> I've logged onto myVolkswagen co uk and accepted the agreement, and the intergration is still not loading. I also did this a few weeks ago and it fixed the issue last time.
> 
> Error logs after accepting the agreement today
> 
> 2023-03-05 19:13:12.844 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.volkswagen_we_connect_id.sensor 2023-03-05 19:13:12.849 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform volkswagen_we_connect_id.sensor: Platform not found (Exception importing custom_components.volkswagen_we_connect_id.sensor).

Try logging in on myvolkswagen.de. I’m not in Germany, but logging on to the .de site fixes it for me.

**Comment by SwannyBFC** [comment]
Tried the de site and still not loading for me

**Comment by soeffi** [comment]
Same here. I logged into .de site and accepted the conditions. Issue persisted, so I removed the integration and readded:

Adding the integration took very long. Although is finally reported success, the log shows
`Setup of platform volkswagen_we_connect_id is taking longer than 60 seconds. Startup will proceed without waiting any longer`
and does not work

**Comment by jacobstim** [comment]
To provide some more information: after accepting the T&C's on the myvolkswagen.de site, the error message changes and becomes this:

```
Error setting up entry Volkswagen We Connect ID for volkswagen_we_connect_id
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 47, in async_setup_entry
    await hass.async_add_executor_job(_we_connect.login)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 184, in login
    self.__session.login()
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 77, in login
    self.fetchTokens('https://emea.bff.cariad.digital/user-login/login/v1',
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 298, in fetchTokens
    raise TemporaryAuthentificationError(f'Token could not be fetched due to temporary WeConnect failure: {tokenResponse.status_code}')
weconnect.errors.TemporaryAuthentificationError: Token could not be fetched due to temporary WeConnect failure: 504
```

The fact that it says "temporary error" and a 504 gives me some hope that it will fix itself after a while :).

**Comment by gednet** [comment]
I have the same issue. Integration not working :( 

Is there any solution to this issue?

> Logger: homeassistant.config_entries
> Source: custom_components/volkswagen_we_connect_id/__init__.py:47
> Integration: Volkswagen We Connect ID
> First occurred: 18:13:13 (2 occurrences)
> Last logged: 18:20:50
> 
> Error setting up entry Volkswagen We Connect ID for volkswagen_we_connect_id
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
>     result = await component.async_setup_entry(hass, self)
>   File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 47, in async_setup_entry
>     await hass.async_add_executor_job(_we_connect.login)
>   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 184, in login
>     self.__session.login()
>   File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 77, in login
>     self.fetchTokens('https://emea.bff.cariad.digital/user-login/login/v1',
>   File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 298, in fetchTokens
>     raise TemporaryAuthentificationError(f'Token could not be fetched due to temporary WeConnect failure: {tokenResponse.status_code}')
> weconnect.errors.TemporaryAuthentificationError: Token could not be fetched due to temporary WeConnect failure: 504

**Comment by PaulProjects** [comment]
I had the same problem and other then just reloading the integration restarting HA solved it for me.

**Comment by Maxi531** [comment]
So I have restarted the integration, restarted HA and done a full reinstall of the integration via HACS, and I'm still getting this error:

```
This error originated from a custom integration.

Logger: custom_components.volkswagen_we_connect_id
Source: custom_components/volkswagen_we_connect_id/__init__.py:53
Integration: Volkswagen We Connect ID
First occurred: 07:48:25 (1 occurrences)
Last logged: 07:48:25

Unexpected error fetching volkswagen_we_connect_id data: Could not fetch data. Status Code was: 502
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 195, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 53, in async_update_data
    await hass.async_add_executor_job(_we_connect.update)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 193, in update
    self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 202, in updateVehicles
    data = self.fetchData(url, force)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 388, in fetchData
    raise RetrievalError(f'Could not fetch data. Status Code was: {statusResponse.status_code}')
weconnect.errors.RetrievalError: Could not fetch data. Status Code was: 502

```
![image](https://user-images.githubusercontent.com/82330572/223667193-f0880dd5-78f8-48ab-83b5-c01ebe98946f.png)

It still somehow works, see picture, but if I have to restart HA for a update or anyhting else, it stops working, meaning I have to delete WC ID, restart HA, redownload WC ID, restart HA, and then I can add the container again, but get the same error, eventhough the devices are detected.
