### ISSUE TITLE
Integration fails to start after HA update

### ISSUE THREAD

**Issue by roppenheimer** [mitch-dc/volkswagen_we_connect_id#174]
I just updated my HA to the latest release and the integration failed to start.

The log entry I get is as follows:

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/volkswagen_we_connect_id/__init__.py:47
Integration: Volkswagen We Connect ID
First occurred: 8:30:45 AM (2 occurrences)
Last logged: 8:31:44 AM

Error setting up entry Volkswagen We Connect ID for volkswagen_we_connect_id
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 47, in async_setup_entry
    await hass.async_add_executor_job(_we_connect.login)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 184, in login
    self.__session.login()
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
    response = self.doWebAuth(authorizationUrl)
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 243, in doWebAuth
    raise APICompatibilityError('No user id provided')
weconnect.errors.APICompatibilityError: No user id provided

RPi 4 - 8GB 
Home Assistant 2023.3.6
Supervisor 2023.03.1
Operating System 9.5
Frontend 20230309.1 - latest

**Comment by flixlix** [comment]
Please close this issue, since it is solved

**Comment by mpschr** [comment]
@roppenheimer what exactly was it you needed to do? I may have the same issue..

**Comment by roppenheimer** [comment]
@mpschr Log in to your My Volkswagen account. Accept any consents you are presented with. Re-start the integration.

**Comment by mpschr** [comment]
Thanks @roppenheimer 

It helped getting rid of an error - but for some reason the integration is not serving the device and its sensors anymore...
