### ISSUE TITLE
We Connect service not avaible (beacuse of issue / outage on Volkswagen)

### ISSUE THREAD

**Issue by jovana** [mitch-dc/volkswagen_we_connect_id#192]
## Describe the bug
Yesterday there was an outage at Volkswagen (see also this report: https://downdetector.co.uk/status/we-connect-go/)
This results in the not working of this integration anymore, which makes sense of course. I notice a bunch of errors putting every 30 seconds into the log file.

Is it possible to have a global detection if data can be retrieved if not retry or pause of a few minutes?

## Debug log
This is the error related to the outage (line number can be different because I have some modifications):
```
  File "/config/custom_components/volkswagen_we_connect_id/number.py", line 70, in native_value
    if self.data.domains["charging"]["chargingSettings"].targetSOC_pct.value:
       ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'charging'
```

This is the whole error each 30 sec:
```
2023-07-14 16:36:21.984 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 229, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 374, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 431, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 596, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 374, in state
    return self.value
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 427, in value
    if (native_value := self.native_value) is None:
                        ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/volkswagen_we_connect_id/number.py", line 70, in native_value
    if self.data.domains["charging"]["chargingSettings"].targetSOC_pct.value:
       ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'charging'
```

## Version of the custom_component
1.0

## Configuration
N/A

**Comment by Zloysisk** [comment]
Good day too all. After 31/12/2024 the we connect go will shut down. But OBD device will still working, and I have a question, how it will use without application ?
