### ISSUE TITLE
Unavailable

### ISSUE THREAD

**Issue by superharaldsson** [mitch-dc/volkswagen_we_connect_id#215]
After updared the id.4 to 3.2 my sensors get unavailable, us there a fix for this or is it a setup in the car?

**Comment by superharaldsson** [comment]
Felet härrör från en anpassad integration.

Logger: custom_components.volkswagen_we_connect_id
Source: helpers/update_coordinator.py:290
Integration: Volkswagen We Connect ID
First occurred: 09:42:47 (12 occurrences)
Last logged: 09:59:11

Unexpected error fetching volkswagen_we_connect_id data: Could not fetch data. Status Code was: 403
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 246, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 53, in async_update_data
    await hass.async_add_executor_job(_we_connect.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/weconnect/weconnect.py", line 193, in update
    self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
  File "/usr/local/lib/python3.11/site-packages/weconnect/weconnect.py", line 202, in updateVehicles
    data = self.fetchData(url, force)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/weconnect/weconnect.py", line 388, in fetchData
    raise RetrievalError(f'Could not fetch data. Status Code was: {statusResponse.status_code}')
weconnect.errors.RetrievalError: Could not fetch data. Status Code was: 403

**Comment by superharaldsson** [comment]
Logger: weconnect
Source: /usr/local/lib/python3.11/site-packages/weconnect/elements/vehicle.py:432
First occurred: 09:42:12 (21 occurrences)
Last logged: 09:58:41

Failed downloading picture door_right_back_overlay with status code 403 will try again in next update
Failed downloading picture window_left_front_overlay with status code 403 will try again in next update
Failed downloading picture light_right with status code 403 will try again in next update
Failed downloading picture window_right_back_overlay with status code 403 will try again in next update
Failed downloading picture door_left_back with status code 403 will try again in next update

**Comment by superharaldsson** [comment]
Logger: weconnect
Source: /usr/local/lib/python3.11/site-packages/weconnect/elements/vehicle.py:348
First occurred: 09:40:40 (31 occurrences)
Last logged: 09:58:37

/vehicles/WVGZZZE2ZMP015610: Unknown attribute fuelLevelStatus with value {'value': {'carCapturedTimestamp': '2023-10-22T07:39:31.418Z', 'currentSOC_pct': 38, 'primaryEngineType': 'electric', 'carType': 'electric'}} in domain measurements
/vehicles/WVGZZZE2ZMP015610: Unknown attribute fuelLevelStatus with value {'value': {'carCapturedTimestamp': '2023-10-22T07:44:52.647Z', 'currentSOC_pct': 39, 'primaryEngineType': 'electric', 'carType': 'electric'}} in domain measurements
/vehicles/WVGZZZE2ZMP015610: Unknown attribute fuelLevelStatus with value {'value': {'carCapturedTimestamp': '2023-10-22T07:50:56.575Z', 'currentSOC_pct': 40, 'primaryEngineType': 'electric', 'carType': 'electric'}} in domain measurements
/vehicles/WVGZZZE2ZMP015610: Unknown attribute fuelLevelStatus with value {'value': {'carCapturedTimestamp': '2023-10-22T07:58:28.148Z', 'currentSOC_pct': 41, 'primaryEngineType': 'electric', 'carType': 'electric'}} in domain measurements

**Comment by superharaldsson** [comment]
I have this in the log

**Comment by superharaldsson** [comment]
Logger: homeassistant.config_entries
Source: config_entries.py:399
First occurred: 09:46:33 (6 occurrences)
Last logged: 09:51:40

Error setting up entry Volkswagen We Connect ID for sensor
Error setting up entry Volkswagen We Connect ID for number
Error setting up entry Volkswagen We Connect ID for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 126, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 195, in async_setup_entry
    return await self._platforms[key].async_setup_entry(config_entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in async_setup_entry
    return await self._async_setup_platform(async_create_setup_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
asyncio.exceptions.CancelledError: aiohttp connection lost

**Comment by superharaldsson** [comment]
Logger: homeassistant.config_entries
Source: config_entries.py:399
First occurred: 09:44:09 (5 occurrences)
Last logged: 09:49:58

Error setting up entry Volkswagen We Connect ID for volkswagen_we_connect_id
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 47, in async_setup_entry
    await hass.async_add_executor_job(_we_connect.login)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/weconnect/weconnect.py", line 184, in login
    self.__session.login()
  File "/usr/local/lib/python3.11/site-packages/weconnect/auth/we_connect_session.py", line 75, in login
    authorizationUrl = self.authorizationUrl(url='https://identity.vwgroup.io/oidc/v1/authorize')
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/weconnect/auth/we_connect_session.py", line 96, in authorizationUrl
    redirect = tryLoginResponse.headers['Location']
               ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'location'

**Comment by rgerhards** [comment]
Just FYI: VW seems to have large issues with their software (backend?) again. Even the VW App acts very erratic, and sometimes permits me to start/stop charging while at other times does not. Also it claims that I have no connection servcies contract, while on the web it shows I have till 2026 ;-)

In short words: check with the App, I guess this issue is unrelated to the integration. The integration seems to be far more solid than the paid-for VW software. My next car is probably not a VW because of all the garbage software ;-)

**Comment by llhotka** [comment]
I am experiencing the same with infotainment version 3.5. I believe it has to do with the option **Send location data** (in user privacy configuration) that unfortunately keep turning off spontaneously after I turn it on. I tried to harass WeConnect support with this but haven't got any reply from them yet.

**Comment by Henke19822** [comment]
Yep, same issue for me. All sensors turn "Unavailable" quite frequently. Issue started some weeks ago and remains, eventhough VWs app works good again.

**Comment by rgerhards** [comment]
> I tried to harass WeConnect support with this but haven't got any reply from them yet.

I had success with that. And let me tell you that you missed nothing ;-)

**Comment by rgerhards** [comment]
> Yep, same issue for me. All sensors turn "Unavailable" quite frequently. Issue started some weeks ago and remains, eventhough VWs app works good again.

Did you increase the polling period in the integration's startup source to 90 seconds? It looks like VW has silently introduced/limited a rate limit. Once I did this, the integration works.

But beware: *since around late friday (Nov, 3rd) evening, the API does not work in any way, also not via the app.* All in all, the VW API (not the integration!) is crap and totally unreliable.

**Comment by llhotka** [comment]
> > I tried to harass WeConnect support with this but haven't got any reply from them yet.
> 
> I had success with that. And let me tell you that you missed nothing ;-)

In the mean time, I also received a reply. They want me to send some screenshots. :-)

**Comment by llhotka** [comment]
> > Yep, same issue for me. All sensors turn "Unavailable" quite frequently. Issue started some weeks ago and remains, eventhough VWs app works good again.
> 
> Did you increase the polling period in the integration's startup source to 90 seconds? It looks like VW has silently introduced/limited a rate limit. Once I did this, the integration works.
> 
> But beware: **since around late friday (Nov, 3rd) evening, the API does not work in any way, also not via the vw app.** All in all, the VW API (not the integration!) is crap and totally unreliable.



> Did you increase the polling period in the integration's startup source to 90 seconds? It looks like VW has silently introduced/limited a rate limit. Once I did this, the integration works.

Hmm, already now the integration makes restarting HA somewhat painful. :-/

> 
> But beware: **since around late friday (Nov, 3rd) evening, the API does not work in any way, also not via the vw app.** All in all, the VW API (not the integration!) is crap and totally unreliable.

It seems to work now, but for how long? I totally agree with the conclusion. Audi is now migrating to Google Automotive, which might happen to the whole VW concern, sooner or later.
