### ISSUE TITLE
Colour Space error stopping integration from loading

### ISSUE THREAD

**Issue by rinosaur681** [mitch-dc/volkswagen_we_connect_id#217]
## Version of the custom_component
0.1.9

## Installation method (hacs / manual)
HACS

## Installation method of hass (venv, docker, hassio,...)
Hassio

## Describe the bug

Integration fails to start, I assumed it was part of the wider issue for the previous 0.1.8 version but the change doesn't seem to have helped it. It seems like it is some sort of issue for an image, not understanding the correct colour space or something and then fails out no matter if I try an reinstall or restart the integration. 

## Debug log

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 48, in async_setup_entry
    await hass.async_add_executor_job(_we_connect.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/weconnect/weconnect.py", line 193, in update
    self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
  File "/usr/local/lib/python3.11/site-packages/weconnect/weconnect.py", line 213, in updateVehicles
    vehicle = Vehicle(weConnect=self, vin=vin, parent=self.__vehicles, fromDict=vehicleDict, fixAPI=self.fixAPI,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/weconnect/elements/vehicle.py", line 126, in __init__
    self.update(fromDict, updateCapabilities=updateCapabilities, updatePictures=updatePictures, selective=selective)
  File "/usr/local/lib/python3.11/site-packages/weconnect/elements/vehicle.py", line 227, in update
    self.updatePictures()
  File "/usr/local/lib/python3.11/site-packages/weconnect/elements/vehicle.py", line 457, in updatePictures
    self.updateStatusPicture()
  File "/usr/local/lib/python3.11/site-packages/weconnect/elements/vehicle.py", line 589, in updateStatusPicture
    draw.ellipse(((imgWidth - 100), warningLightoffset, (imgWidth - 1), (warningLightoffset + 100)), fill=(0, 0, 0, 200))
  File "/usr/local/lib/python3.11/site-packages/PIL/ImageDraw.py", line 162, in ellipse
    ink, fill = self._getink(outline, fill)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PIL/ImageDraw.py", line 133, in _getink
    fill = self.palette.getcolor(fill, self._image)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PIL/ImagePalette.py", line 118, in getcolor
    raise ValueError(msg)
ValueError: cannot add non-opaque RGBA color to RGB palette

**Comment by rinosaur681** [comment]
I implemented the changes in PR#219 and it seems to have fixed the problem
