### ISSUE TITLE
'No User ID Provided' - can't add Integration

### ISSUE THREAD

**Issue by gmarchment** [mitch-dc/volkswagen_we_connect_id#230]
Trying to add as an Integration in HA.  I add in a correct VW ID Username/Password - tested and working separately on their site.  I get a red 'unknown error' with the error log below

## Version of the custom_component
v0.1.19

## Installation method (hacs / manual)
HACS

## Configuration

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

## Describe the bug

Not connecting to VW ID

## Debug log

This error originated from a custom integration.

Logger: custom_components.volkswagen_we_connect_id.config_flow
Source: custom_components/volkswagen_we_connect_id/config_flow.py:64
Integration: Volkswagen We Connect ID
First occurred: 07:35:09 (4 occurrences)
Last logged: 07:38:37

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/volkswagen_we_connect_id/config_flow.py", line 64, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/volkswagen_we_connect_id/config_flow.py", line 39, in validate_input
    await hass.async_add_executor_job(we_connect.login)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/weconnect/weconnect.py", line 184, in login
    self.__session.login()
  File "/usr/local/lib/python3.11/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
    response = self.doWebAuth(authorizationUrl)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/weconnect/auth/we_connect_session.py", line 243, in doWebAuth
    raise APICompatibilityError('No user id provided. A possible reason is that you have to reconfirm the terms and conditions.')
weconnect.errors.APICompatibilityError: No user id provided. A possible reason is that you have to reconfirm the terms and conditions.

**Comment by wimfarasyn** [comment]
Was having the same issue - when logging in to the We Connect website, there were a couple of advertising options I had to confirm/decline until arriving at the actual We Connect pages. After that, the integration worked fine. (v0.2.0)

**Comment by timconinx** [comment]
OMG... I was having the same issue as well, although having had a working integration. It just stopped working.
I went to the We Connect website (which already showed the information correctly) and had to log in to, and agree with the Volkswagen WeConnect Shop(!) connection, including ads being served to the app!
After that, the integration worked again.

Some serious @internetofshit issues here 😞
