### ISSUE TITLE
Version not compatible with HA2024-11.3

### ISSUE THREAD

**Issue by bobbasli** [mitch-dc/volkswagen_we_connect_id#284]
Hi,

It looks as if the weconnect is not compatible.
Weconnect can not be loaded in the latest version 

Log:

Logger: homeassistant.config_entries
Bron: config_entries.py:635
Eerst voorgekomen: 20:04:47 (3 gebeurtenissen)
Laatst gelogd: 21:37:20

Error setting up entry Volkswagen We Connect ID for volkswagen_we_connect_id
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 57, in async_setup_entry
    await hass.async_add_executor_job(_we_connect.login)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/weconnect/weconnect.py", line 184, in login
    self.__session.login()
  File "/usr/local/lib/python3.12/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
    response = self.doWebAuth(authorizationUrl)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/weconnect/auth/we_connect_session.py", line 253, in doWebAuth
    afterLoginResponse = self.get(afterLoginUrl, allow_redirects=False, access_type=AccessType.NONE)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/weconnect/auth/we_connect_session.py", line 69, in request
    return super(WeConnectSession, self).request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/weconnect/auth/openid_session.py", line 188, in request
    raise InsecureTransportError()
oauthlib.oauth2.rfc6749.errors.InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.

**Comment by gilder0** [comment]
in my opinion something has changed during last few days in VW API. 
I got exactly the same error with older HA version.

**Comment by bjhemm** [comment]
I had the exact same problem. But this fixed it for me.  I logged in at https://id.vwgroup.io/landing-page and was shown a "you have to agree to....." It seems that you have consent to some new terms and conditions.
After that the integration started working again.

**Comment by mark-summers** [comment]
> I had the exact same problem. But this fixed it for me.  I logged in at https://id.vwgroup.io/landing-page and was shown a "you have to agree to....." It seems that you have consent to some new terms and conditions.
> 
> After that the integration started working again.

Thank you! This worked for me!

**Comment by MCBrakel** [comment]
> I had the exact same problem. But this fixed it for me. I logged in at https://id.vwgroup.io/landing-page and was shown a "you have to agree to....." It seems that you have consent to some new terms and conditions. After that the integration started working again.

This also solved the issue here. Thanks!

**Comment by frosenlind** [comment]
> I had the exact same problem. But this fixed it for me. I logged in at https://id.vwgroup.io/landing-page and was shown a "you have to agree to....." It seems that you have consent to some new terms and conditions. After that the integration started working again.

Same here, thank you!

**Comment by bobbasli** [comment]
Awesome, that does the trick!

**Comment by visualapproach** [comment]
Thanks, that was it!

**Comment by ccie11827** [comment]
Thanks, that solves my problem!

**Comment by bobbasli** [comment]
> I had the exact same problem. But this fixed it for me. I logged in at https://id.vwgroup.io/landing-page and was shown a "you have to agree to....." It seems that you have consent to some new terms and conditions. After that the integration started working again.

This solves the issue
