### ISSUE TITLE
Integrate Cupra Born

### ISSUE THREAD

**Issue by initdebugs** [mitch-dc/volkswagen_we_connect_id#40]
As of now, it is not working for my Cupra Born. Could you please implement this as well?

**Comment by mitch-dc** [comment]
First changes in the weconnect libary are added for Cupra Born, if the work is done there i will try to add it. 
Don't now if i need to change the name for the integration after this tough :P

**Comment by delcara** [comment]
I offered the the developer of https://github.com/tillsteinbach/WeConnect-python which is used by this intergration access to My Cupra account to add the Cupra Born into the weconnect library. Hopefully he will add this. When that's done it can be added here and offcourse I can offer acces to My Cupra account for testing.

**Comment by My-userid** [comment]
I have a Cupra Born too and seems they got it working in the WeConnect-python library.

**Comment by BePulverized** [comment]
There is an open issue https://github.com/tillsteinbach/WeConnect-python/issues/26 where I and a couple of others are offering help getting the python script going. Early tests are succesful and I can actually show info from my Cupra Born in the python application.

**Comment by alangibson** [comment]
I'd appreciate it if anyone with a VW could go to the above issue and test my changes. I have a Cupra Born, so I can't regression test the existing VW support.

**Comment by alangibson** [comment]
I've got basic sensor integration with Home Assistant using the volkswagen_we_connect_id integration going here:

https://github.com/alangibson/volkswagen_we_connect_id/tree/feature/cupra-support

Caveats:

- Buttons don't work
- Climate sensors don't work
- I haven't tested sensors during active charging yet

**Comment by alangibson** [comment]
My changes are now quite complete for charging. Test it out with:

```
ssh root@homeassistant.local
git clone -b 'feature/cupra-support' https://github.com/alangibson/volkswagen_we_connect_id.git
cp -R volkswagen_we_connect_id/custom_components/volkswagen_we_connect_id /config/custom_components/
ha core restart
```

**Comment by xLexip** [comment]
Hey @alangibson, 
if I remember correctly, i'm using your fork (feature branch) for our born. The integration fails for a few days now and no data can be received at all. Does it still work for you and do you have a clue on what's wrong? Thanks in advance.

> This error originated from a custom integration.
> 
> Logger: homeassistant.config_entries
> Source: custom_components/volkswagen_we_connect_id/__init__.py:92
> Integration: Volkswagen We Connect ID (documentation)
> First occurred: 12:42:29 PM (3 occurrences)
> Last logged: 1:18:07 PM
> 
> Error setting up entry Volkswagen We Connect ID for volkswagen_we_connect_id
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
>     result = await component.async_setup_entry(hass, self)
>   File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 92, in async_setup_entry
>     hass.config_entries.async_setup_platforms(entry, PLATFORMS)
> AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
