### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'insufficientBatteryLevelWarning'

### ISSUE THREAD

**Issue by woutercoppens** [mitch-dc/volkswagen_we_connect_id#46]
## Version of the custom_component
OS Version:               Home Assistant OS 8.2
Home Assistant Core:      2022.7.5
volkswagen_we_connect_id: v0.0.11

Volkswagen id4 - software v2.3

## Installation method (hacs / manual)
hacs

## Installation method of hass (venv, docker, hassio,...)
hassio

## Configuration
N/A
## Describe the bug
The logfile is filling with this warning

## Debug log
```
2022-07-19 19:26:19 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 339, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 209, in state
    if (is_on := self.is_on) is None:
  File "/config/custom_components/volkswagen_we_connect_id/binary_sensor.py", line 171, in is_on
    state = self.entity_description.value(self.data.domains)
  File "/config/custom_components/volkswagen_we_connect_id/binary_sensor.py", line 109, in <lambda>
    ].connectionWarning.insufficientBatteryLevelWarning.value,
AttributeError: 'NoneType' object has no attribute 'insufficientBatteryLevelWarning'

```

**Comment by mitch-dc** [comment]
Got the same, not only on this sensor but on more. The api does not return these anymore. 
Update is coming.
