### ISSUE TITLE
conflicting dependencies

### ISSUE THREAD

**Issue by jortsl** [mitch-dc/volkswagen_we_connect_id#70]
# Version of the custom_component

v0.0.13
# Installation method (hacs / manual)

HACS
# Installation method of hass (venv, docker, hassio,...)
iocage jail with Truenas
HA version: Home Assistant Core 2022.6.6

# Describe the bug
Attempting to install the integration in Home Assistant gives a twirly wait icon for a while, then I get the message "Config flow could not be loaded: undefined" 

# Debug log
First I got:
```
Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: 16:09:22 (3 occurrences)
Last logged: 16:09:25

Unable to install package weconnect==0.45.1: ERROR: Cannot install weconnect==0.45.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```
After a retry I got:
```
Logger: aiohttp.server
Source: requirements.py:194
First occurred: 16:09:25 (1 occurrences)
Last logged: 16:09:25

Error handling request
Traceback (most recent call last):
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/auth.py", line 220, in auth_middleware
    return await handler(request)
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/homeassistant/components/config/config_entries.py", line 173, in post
    return await super().post(request)
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/data_entry_flow.py", line 70, in post
    result = await self._flow_mgr.async_init(
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 205, in async_init
    flow, result = await task
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 223, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/homeassistant/config_entries.py", line 744, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/homeassistant/setup.py", line 360, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/homeassistant/requirements.py", line 83, in async_get_integration_with_requirements
    await _async_process_integration(hass, integration, done)
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/homeassistant/requirements.py", line 99, in _async_process_integration
    await async_process_requirements(
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/homeassistant/requirements.py", line 162, in async_process_requirements
    await _async_process_requirements(
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/homeassistant/requirements.py", line 194, in _async_process_requirements
    raise RequirementsNotFound(name, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for volkswagen_we_connect_id not found: ['weconnect==0.45.1'].

```

**Comment by tsg21** [comment]
This has come up before. The problem is that this library has a transitive dependency on a version of `requests` that does not match the version that is mandated by homeassistant core.

The quick answer/fix is to upgrade your version of homeassistant. You are on 2022.6.6 which is a few months out of date. If you cannot do that, try an older version of this library.

The better fix is to somehow tell homeassistant to ignore the version of requests specified by `weconnect` and just use its own, but I don't know how to do that.

**Comment by jortsl** [comment]
Thanks for your reply. I'll go work on this :)
