### ISSUE TITLE
503 error

### ISSUE THREAD

**Issue by SwannyBFC** [mitch-dc/volkswagen_we_connect_id#77]
Anyone else getting 503 error and the sensors all showing unavailable ? 

2022-10-24 18:23:54.552 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration volkswagen_we_connect_id which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-24 18:24:12.798 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Volkswagen We Connect ID for volkswagen_we_connect_id
File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 41, in async_setup_entry

Log Details (ERROR)
This error originated from a custom integration.
Logger: homeassistant.config_entries
Source: custom_components/volkswagen_we_connect_id/__init__.py:41
Integration: Volkswagen We Connect ID ([documentation](https://github.com/mitch-dc/volkswagen_we_connect_id))
First occurred: 18:24:12 (1 occurrences)
Last logged: 18:24:12

Error setting up entry Volkswagen We Connect ID for volkswagen_we_connect_id
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 41, in async_setup_entry
    await hass.async_add_executor_job(_we_connect.update)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 178, in update
    self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 185, in updateVehicles
    data = self.fetchData(url, force)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 368, in fetchData
    raise RetrievalError(f'Could not fetch data. Status Code was: {statusResponse.status_code}')
weconnect.errors.RetrievalError: Could not fetch data. Status Code was: 404

**Comment by joakimberglund** [comment]
Getting exactly the same

**Comment by keylogicjohan** [comment]
Same here

**Comment by BaukeDeVries** [comment]
Same here

**Comment by vantech14** [comment]
It's fixed now, maybe a cloud issue

**Comment by SwannyBFC** [comment]
We connect cloud issue

**Comment by FirstRulez** [comment]
I am having the same issues. Point to note:
the WeConnect ID. app on iOS is also not working, and Ohme is also not able to connect to the We Connect cloud.

**Comment by mitch-dc** [comment]
VW Api was down. :(
